In [1]:
import numpy as np
x1=np.array([5,0,3,3,7,9])
x1[0]

5

In [2]:
x1[4]

7

In [3]:
x1[-1]

9

In [4]:
x1[-2]

7

In [5]:
np.random.seed(0)
x2=np.random.randint(10, size=(3,4))
print(x2)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [6]:
x2[0,0]

5

In [7]:
x2[2,1]

4

In [8]:
x2[2,-3]

4

In [9]:
x2[0,0]=12
print(x2)

[[12  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]]


In [10]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
x[:5]

array([0, 1, 2, 3, 4])

In [12]:
x[5:]

array([5, 6, 7, 8, 9])

In [13]:
x[4:7]

array([4, 5, 6])

In [15]:
x[::2]

array([0, 2, 4, 6, 8])

In [16]:
x[5:-1:]

array([5, 6, 7, 8])

In [17]:
x[5::-2]

array([5, 3, 1])

In [18]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [19]:
np.random.seed(0)
x3=np.random.randint(10, size=(3,4))
print(x3)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [20]:
x3[:2,:3]

array([[5, 0, 3],
       [7, 9, 3]])

In [21]:
x3[:3,::2]

array([[5, 3],
       [7, 3],
       [2, 7]])

In [22]:
x3[::-1,::-1]

array([[6, 7, 4, 2],
       [5, 3, 9, 7],
       [3, 3, 0, 5]])

In [23]:
x3[:,0]

array([5, 7, 2])

In [24]:
x3[0,:]

array([5, 0, 3, 3])

In [25]:
v1=np.array([1,2,3])
print(v1.shape)
print(v1[0])
print(v1[0:])

(3,)
1
[1 2 3]


In [30]:
v3=np.array([[1,2,3],[4,5,6]])
print(v3)
print(v3.shape)  
print(v3[0])  
print(v3[0][0])  
print(v3[0:1,0:2])

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3]
1
[[1 2]]


In [33]:
v1=np.array([[[1,2,3],[1,4,0]],[[5,6,7],[9,8,7]]])
print(v1)
print(v1.shape)
print(v1[1][1][0])
print(v1[1][1])
print(v1[1])
print(v1[0:1,1:2,1:2])

[[[1 2 3]
  [1 4 0]]

 [[5 6 7]
  [9 8 7]]]
(2, 2, 3)
9
[9 8 7]
[[5 6 7]
 [9 8 7]]
[[[4]]]


In [34]:
print(v1[::])

[[[1 2 3]
  [1 4 0]]

 [[5 6 7]
  [9 8 7]]]


In [35]:
#矩陣轉置
grid=np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
a=np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [39]:
for x in range(1,10):
    print(x,end=' ')

1 2 3 4 5 6 7 8 9 

In [41]:
x=np.array([[1,2,3,4,5,6]])
x.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
x.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [48]:
#一維轉二維要使用np.newaxis
z=np.array([1,2,3])
z[np.newaxis,:]

array([[1, 2, 3]])

In [49]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

In [50]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [51]:
grid=np.array([[1,2,3],[4,5,6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [52]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [53]:
np.concatenate([grid,grid],axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [2]:
x=np.array([1,2,3])
grid=np.array([[9,8,7],[6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [3]:
y=np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [5]:
x=np.array(range(10))
np.split(x, 2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [10]:
A = np.arange(12).reshape(3,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
np.split(A, 2, axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [22]:
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [21]:
np.split(A, 3, axis=0)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [13]:
x=[1,2,3,4,5,6,7,8]
print(x)
x1,x2,x3=np.split(x,[2,5])
print(x1,x2,x3)

[1, 2, 3, 4, 5, 6, 7, 8]
[1 2] [3 4 5] [6 7 8]


In [16]:
harr = np.floor(10 * np.random.random((3, 6)))
print(harr)
print(np.vsplit(harr, 3))

[[2. 4. 7. 0. 1. 4.]
 [8. 9. 5. 2. 6. 8.]
 [6. 4. 1. 4. 4. 4.]]
[array([[2., 4., 7., 0., 1., 4.]]), array([[8., 9., 5., 2., 6., 8.]]), array([[6., 4., 1., 4., 4., 4.]])]


In [17]:
harr = np.floor(10 * np.random.random((2, 6)))
print(harr)
print(np.hsplit(harr, 3))

[[2. 6. 6. 2. 1. 9.]
 [8. 5. 8. 1. 1. 8.]]
[array([[2., 6.],
       [8., 5.]]), array([[6., 2.],
       [8., 1.]]), array([[1., 9.],
       [1., 8.]])]
