In [2]:
import numpy as np
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [5]:
a0=[1,3,5,7,9]
type(a0)

list

In [9]:
type(np.array(a0))

numpy.ndarray

In [7]:
np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [10]:
np.array([1,3.1,5,7,9])
#numpy的全部型別都一樣

array([1. , 3.1, 5. , 7. , 9. ])

In [11]:
np.array([1,3,'5',7,9])
#https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.dtype.html

array(['1', '3', '5', '7', '9'], dtype='<U11')

In [12]:
np.array([1,3,'5',7,9], dtype='str')

array(['1', '3', '5', '7', '9'], dtype='<U1')

In [13]:
np.array([range(1,3)])

array([[1, 2]])

In [14]:
np.array([range(i,i+3) for i in [2,4,6]])
#i從2開始算3個

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [3]:
np.zeros((10), dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3,5),dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
np.full((3,5),1.14)
#2個[[表示2維

array([[1.14, 1.14, 1.14, 1.14, 1.14],
       [1.14, 1.14, 1.14, 1.14, 1.14],
       [1.14, 1.14, 1.14, 1.14, 1.14]])

In [6]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.linspace(0,1,5)
#從0-1分5等分

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.random.random((3,3))

array([[0.16489463, 0.52978199, 0.19146914],
       [0.69504209, 0.67495664, 0.92646969],
       [0.08034903, 0.46893738, 0.09798298]])

In [9]:
np.random.randint(0,10,(3,3))

array([[0, 1, 0],
       [5, 7, 3],
       [1, 1, 1]])

In [10]:
np.random.randint(0,10,(3,4))

array([[6, 6, 9, 6],
       [6, 4, 5, 9],
       [9, 6, 5, 9]])

In [12]:
#random 0-1的小數
np.random.random(1)

array([0.32322404])

In [15]:
np.random.random((3,3))

array([[0.01491297, 0.95496195, 0.00498144],
       [0.0577511 , 0.37952091, 0.91903003],
       [0.90414229, 0.54004639, 0.32261068]])

In [17]:
#給定種子產生固定的random號碼
np.random.seed(0)
np.random.random(1)

array([0.5488135])

In [18]:
#跟下面比較產生大量亂數的時間
L=np.random.random(2000000)
%timeit sum(L)
#Jupiter的指令%timeit

154 ms ± 1.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [19]:
%timeit np.sum(L)

2.52 ms ± 70.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
a2=np.array([[1,2,3],[4,5,6]])
print(a2)
a2.dtype

[[1 2 3]
 [4 5 6]]


dtype('int32')

In [21]:
#dimention 2維
a2.ndim

2

In [22]:
#形狀是2*3
a2.shape

(2, 3)

In [23]:
#元素個數
a2.size

6

In [24]:
#一個陣列的一個內容有幾個byte
a2.itemsize

4

In [30]:
#3維
a3=np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(a3)
a3.dtype

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


dtype('int32')

In [27]:
a3.ndim

3

In [26]:
a3.shape

(2, 2, 3)

In [28]:
a3.size

12

In [29]:
a3.itemsize

4

In [31]:
#12*4
a3.nbytes

48

In [34]:
#用size來表達
np.random.seed(0)
x1=np.random.randint(10,size=6)
print(x1)

[5 0 3 3 7 9]


In [40]:
x1.ndim

1

In [41]:
#1維的顯示方式後面會有逗號
x1.shape

(6,)

In [42]:
x1.size

6

In [43]:
np.random.seed(0)
x2=np.random.randint(10,size=(3,4))
print(x2)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [44]:
x2.ndim

2

In [46]:
x2.shape

(3, 4)

In [48]:
x2.size

12

In [49]:
np.random.seed(0)
x3=np.random.randint(10,size=(3,4,5))
print(x3)

[[[5 0 3 3 7]
  [9 3 5 2 4]
  [7 6 8 8 1]
  [6 7 7 8 1]]

 [[5 9 8 9 4]
  [3 0 3 5 0]
  [2 3 8 1 3]
  [3 3 7 0 1]]

 [[9 9 0 4 7]
  [3 2 7 2 0]
  [0 4 5 5 6]
  [8 4 1 4 9]]]


In [50]:
x3.ndim

3

In [51]:
x3.shape

(3, 4, 5)

In [53]:
x3.size

60

In [55]:
x3.itemsize

4

In [56]:
x3.nbytes

240